version = 0.1
[default.deploy.parameters]
stack_name = "binance-order-book-cron"
resolve_s3 = true
s3_prefix = "binance-order-book-cron"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
